<?php
declare(strict_types=1);
require_once __DIR__ . '/includes/session_bootstrap.php';
require_once __DIR__ . '/db_connect.php';
require_once __DIR__ . '/arcade_app/includes/arcade_schema_manager.php';
require_once __DIR__ . '/arcade_app/includes/player_authority.php';
require_once __DIR__ . '/arcade_app/includes/arcade_leaderboard.php';
require_once __DIR__ . '/arcade_app/includes/arcade_workshop.php';
require_once __DIR__ . '/arcade_app/includes/arcade_social.php';
function app_h(mixed $value): string{return htmlspecialchars((string)$value,ENT_QUOTES|ENT_HTML5,'UTF-8');}
if(!isset($pdo)||!($pdo instanceof PDO)){http_response_code(503);exit('Arcade Profile is temporarily unavailable.');}
arcade_schema_ensure($pdo);$name=(string)($_GET['name']??'');$profile=arcade_social_public_profile($pdo,$name);if(!$profile)http_response_code(404);
$rank=null;if($profile&&empty($profile['private'])){$stmt=$pdo->prepare("SELECT customer_id FROM arcade_player_accounts WHERE arcade_name=? LIMIT 1");$stmt->execute([$profile['arcadeName']]);$profileCustomerId=(int)$stmt->fetchColumn();if($profileCustomerId)$rank=arcade_leaderboard_player_rank($pdo,$profileCustomerId,'alltime',arcade_leaderboard_active_season($pdo),[]);}
$returnUrl=(string)($_GET['return']??'/arcade_leaderboard.php');if(!str_starts_with($returnUrl,'/arcade_leaderboard.php'))$returnUrl='/arcade_leaderboard.php';
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title><?= $profile?app_h($profile['arcadeName']).' | ':'' ?>Arcade Player | Diamonds Outta Dirt</title>
<style>
body{margin:0;background:#050607;color:#f5fffb;font-family:monospace}.public-profile{width:min(980px,94vw);margin:0 auto;padding:38px 0 90px}.public-actions{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:18px}.public-actions a{padding:9px 12px;border:1px solid #294039;border-radius:7px;color:#fff;text-decoration:none}.public-actions a:hover{border-color:#00ff9d;color:#00ff9d}.profile-hero{display:grid;grid-template-columns:190px minmax(0,1fr);gap:18px;padding:20px;border:2px solid rgba(0,255,157,.45);border-radius:18px;background:radial-gradient(circle at top right,rgba(0,243,255,.12),transparent 42%),#0a0e10}.profile-hero.border-neon{border-color:#00e8ff}.profile-hero.border-gold{border-color:#ffd15a}.profile-hero.border-diamond{border-color:#a8f8ff}.profile-hero.border-legacy{border-color:#d96cff;box-shadow:0 0 30px rgba(217,108,255,.16)}.profile-character{height:220px;border:1px solid rgba(255,255,255,.1);border-radius:13px;overflow:hidden;background:#030405}.profile-character img{width:100%;height:100%;object-fit:cover;object-position:top center}.eyebrow{color:#00ff9d;font-size:.65rem;letter-spacing:.14em}.profile-hero h1{margin:6px 0 4px;font-size:1.8rem}.profile-character-name{color:#00f3ff;font-size:.72rem}.bio{color:#a0afab;font-size:.72rem;line-height:1.55}.badges{display:flex;gap:7px;flex-wrap:wrap;margin-top:12px}.badges span{padding:6px 9px;border:1px solid rgba(255,255,255,.14);border-radius:999px;font-size:.56rem}.metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:9px;margin-top:16px}.metric,.panel{padding:13px;border:1px solid rgba(255,255,255,.1);border-radius:10px;background:#0a0d0e}.metric small,.metric strong{display:block}.metric small{color:#81908c;font-size:.5rem}.metric strong{margin-top:5px;color:#fff;font-size:.9rem}.sections{display:grid;grid-template-columns:1fr 1fr;gap:13px;margin-top:15px}.panel h2{margin:0 0 10px;font-size:.8rem;color:#00f3ff}.list{display:grid;gap:7px}.list div{padding:8px;border:1px solid rgba(255,255,255,.08);border-radius:7px}.list strong,.list small{display:block}.list strong{font-size:.58rem}.list small{margin-top:3px;color:#82908d;font-size:.48rem}.private,.not-found{padding:30px;border:1px solid rgba(255,255,255,.12);border-radius:14px;background:#0a0d0e;text-align:center}.private h1,.not-found h1{color:#fff}.private p,.not-found p{color:#8d9a97}@media(max-width:700px){.profile-hero{grid-template-columns:1fr}.profile-character{height:300px}.metrics{grid-template-columns:1fr 1fr}.sections{grid-template-columns:1fr}}
</style></head><body>
<?php $header=__DIR__.'/partials/header.php';if(is_file($header))require $header; ?>
<main class="public-profile"><div class="public-actions"><a href="/arcade">Play Arcade</a><a href="<?= app_h($returnUrl) ?>">Back to Leaderboard</a></div>
<?php if(!$profile): ?><section class="not-found"><h1>Player Not Found</h1><p>That Arcade Name does not match an active player profile.</p></section>
<?php elseif(!empty($profile['private'])): ?><section class="private"><div class="eyebrow">PRIVATE ARCADE PROFILE</div><h1><?= app_h($profile['arcadeName']) ?></h1><p>This player has chosen not to display a public profile.</p></section>
<?php else: ?><section class="profile-hero border-<?= app_h($profile['borderKey']) ?>"><div class="profile-character"><img src="/arcade_app/assets/characters/<?= app_h($profile['characterFile']) ?>" alt="<?= app_h($profile['characterName']) ?>"></div><div><div class="eyebrow"><?= app_h(strtoupper($profile['title'])) ?></div><h1><?= app_h($profile['arcadeName']) ?></h1><div class="profile-character-name">Favorite Character · <?= app_h($profile['characterName']) ?></div><?php if($profile['bio']): ?><p class="bio"><?= app_h($profile['bio']) ?></p><?php endif; ?><div class="badges"><?php foreach($profile['badges'] as $badge): ?><span><?= app_h($badge['icon']) ?> <?= app_h($badge['name']) ?></span><?php endforeach; ?><?php if(!$profile['badges']): ?><span>No featured badges selected</span><?php endif; ?></div><div class="metrics"><div class="metric"><small>BEST SCORE</small><strong><?= number_format((int)$profile['metrics']['bestScore']) ?></strong></div><div class="metric"><small>ALL-TIME RANK</small><strong><?= $rank?'#'.number_format((int)$rank):'UNRANKED' ?></strong></div><div class="metric"><small>RUNS</small><strong><?= number_format((int)$profile['metrics']['runs']) ?></strong></div><div class="metric"><small>BOSSES</small><strong><?= number_format((int)$profile['metrics']['bosses']) ?></strong></div><div class="metric"><small>OUTFITS</small><strong><?= number_format((int)$profile['metrics']['outfits']) ?></strong></div><div class="metric"><small>PERFECT</small><strong><?= number_format((int)$profile['metrics']['perfect']) ?></strong></div><div class="metric"><small>WORKSHOP CRAFTS</small><strong><?= number_format((int)$profile['metrics']['workshopCrafts']) ?></strong></div><div class="metric"><small>LONGEST STREAK</small><strong><?= number_format((int)$profile['metrics']['longestStreak']) ?></strong></div></div></div></section>
<div class="sections"><section class="panel"><h2>Workshop Loadout</h2><div class="list"><?php foreach($profile['equipment'] as $slot=>$item): ?><div><strong><?= app_h(strtoupper($slot)) ?></strong><small><?= app_h(ucwords(str_replace('-',' ',$item))) ?></small></div><?php endforeach; ?><?php if(!$profile['equipment']): ?><div><small>No Workshop equipment displayed.</small></div><?php endif; ?></div></section><section class="panel"><h2>Recent Achievements</h2><div class="list"><?php foreach($profile['recentAchievements'] as $item): ?><div><strong><?= app_h($item['name']) ?></strong><small><?= app_h($item['description']) ?></small></div><?php endforeach; ?><?php if(!$profile['recentAchievements']): ?><div><small>No unlocked achievements displayed yet.</small></div><?php endif; ?></div></section><section class="panel"><h2>Season History</h2><div class="list"><?php foreach($profile['seasonHistory'] as $item): ?><div><strong><?= app_h($item['name']) ?></strong><small><?= app_h($item['reward_label']) ?></small></div><?php endforeach; ?><?php if(!$profile['seasonHistory']): ?><div><small>No claimed season rewards yet.</small></div><?php endif; ?></div></section><section class="panel"><h2>Progress</h2><div class="list"><div><strong><?= number_format((int)$profile['metrics']['ownedCharacters']) ?> Characters</strong><small>Owned illustrated cast</small></div><div><strong><?= number_format((int)$profile['metrics']['storyClaims']) ?> / 20 Story Chapters</strong><small>Claimed story progress</small></div><div><strong><?= number_format((int)$profile['metrics']['achievements']) ?> Achievements</strong><small>Unlocked account achievements</small></div></div></section></div>
<?php endif; ?></main></body></html>
